# Generated by Django 5.1.1 on 2025-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ddd',
            field=models.IntegerField(default=11, null=True, verbose_name='DDD'),
        ),
    ]
