# Generated by Django 5.1.1 on 2025-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ddd',
            field=models.IntegerField(blank=True, default=11, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Telefone (só números)'),
        ),
    ]
