# Generated by Django 5.1.1 on 2024-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.CharField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
