# Generated by Django 5.1.1 on 2024-10-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Foto de perfil (opcional)'),
        ),
    ]
