# Generated by Django 5.1.1 on 2025-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
