# Generated by Django 5.1.1 on 2025-02-21 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='fallback_user.png', max_length=255, verbose_name='image'),
        ),
    ]
