# Generated by Django 5.1.1 on 2025-02-21 17:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dkt4xp75j/image/upload/v1740159602/qhq6gsxfm8my9w4wxkxm.png', max_length=255, verbose_name='image'),
        ),
    ]
