# Generated by Django 5.1.1 on 2025-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=9, verbose_name='Telefone (só números)'),
        ),
    ]
