# Generated by Django 5.1.1 on 2025-02-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
    ]
