services:
  silfloresapp:
    container_name: silfloresapp
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./silfloresapp:/silfloresapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./silfloresapp
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"