# fly.toml app configuration file generated for silflores on 2025-02-13T14:34:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'silflores'
primary_region = 'gig'

[build]

[deploy]
  min_machines_running = 1

[metrics]
  [[metrics.rules]]
    name = "High CPU"
    metric = "cpu"
    threshold = 90
    duration = "1m"
    action = "scale_up"
    cooldown = "5m"

  [[metrics.rules]]
    name = "Low CPU"
    metric = "cpu"
    threshold = 40
    duration = "5m"
    action = "scale_down"
    cooldown = "10m"


[env]
  DEBUG='0'
  PAGSEGURO_SANDBOX='1'
  ALLOWED_HOSTS='*'
  PORT='8000'
  EMAIL_HOST='smtp.gmail.com'
  EMAIL_PORT=587
  REDIS_HOST='redis'
  REDIS_PORT=6379
  GOOGLE_APPLICATION_CREDENTIALS = "/silflores-proxy-key.json"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
