# fly.toml app configuration file generated for silflores on 2025-02-10T23:44:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'silflores'
primary_region = 'gru'

[build]
  DEBUG='0'
  PAGSEGURO_SANDBOX='1'
  ALLOWED_HOSTS='*'
  PORT='8080'
  EMAIL_HOST='smtp.gmail.com'
  EMAIL_PORT=587
  REDIS_HOST='redis'
  REDIS_PORT=6379

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
