# fly.toml app configuration file generated for silflores on 2025-02-13T14:34:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'silflores'
primary_region = 'gig'

[build]

[env]
  DEBUG='0'
  PAGSEGURO_SANDBOX='1'
  ALLOWED_HOSTS='*'
  PORT='8000'
  EMAIL_HOST='smtp.gmail.com'
  EMAIL_PORT=587
  REDIS_HOST='redis'
  REDIS_PORT=6379
  GOOGLE_APPLICATION_CREDENTIALS = "/silflores-proxy-key.json"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 2
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    soft_limit = 60
    hard_limit = 80

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
