# Generated by Django 5.1.1 on 2024-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='fullPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
