# Generated by Django 5.1.1 on 2025-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='labelUrl',
            field=models.CharField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='trackingUrl',
            field=models.CharField(default='', null=True),
        ),
    ]
