# Generated by Django 5.1.1 on 2025-02-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='freightOption',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='cart',
            name='freightValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
