# Generated by Django 5.1.1 on 2025-03-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='paymentUrl',
            field=models.CharField(default=''),
        ),
    ]
