# Generated by Django 5.1.1 on 2025-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_paymenturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='trackingUrl',
            field=models.CharField(default=''),
        ),
    ]
