# Generated by Django 5.1.1 on 2025-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_trackingurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='checkoutCreation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='paymentDatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
