# Generated by Django 5.1.1 on 2025-03-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_checkoutcreation_cart_paymentdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='packageData',
            field=models.JSONField(null=True),
        ),
    ]
