# Generated by Django 5.1.1 on 2025-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_packagedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='packageData',
        ),
        migrations.AddField(
            model_name='cart',
            name='shipmentId',
            field=models.CharField(null=True),
        ),
    ]
