# Generated by Django 5.1.1 on 2025-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_melhorenviotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melhorenviotoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='melhorenviotoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
