# Generated by Django 5.1.1 on 2025-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_melhorenviotoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melhorenviotoken',
            name='prev_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
