# Generated by Django 5.1.1 on 2025-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_melhorenviotoken_prev_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='melhorenviotoken',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
