# Generated by Django 5.1.1 on 2025-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_melhorenviotoken_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melhorenviotoken',
            name='code',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
