# Generated by Django 5.1.1 on 2025-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_alter_melhorenviotoken_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melhorenviotoken',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='melhorenviotoken',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
