# Generated by Django 5.1.1 on 2025-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_melhorenviotoken_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melhorenviotoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
