# Generated by Django 5.1.1 on 2025-04-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_alter_melhorenviotoken_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melhorenviotoken',
            name='code',
        ),
    ]
