# Generated by Django 5.1.1 on 2025-04-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_remove_melhorenviotoken_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='labelUrl',
            field=models.CharField(default=''),
        ),
    ]
