# Generated by Django 5.1.1 on 2025-04-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_cart_labelurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='melhorenviotoken',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
