# Generated by Django 5.1.1 on 2025-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_melhorenviotoken_sandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='freightOption',
            field=models.IntegerField(default=0),
        ),
    ]
