# Generated by Django 5.1.1 on 2024-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='numProducts',
            field=models.IntegerField(default=0),
        ),
    ]
