# Generated by Django 5.1.1 on 2024-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('fixed', 'Tamanho fixo'), ('choice', 'Selecionar tamanho'), ('set', 'Definir valor')], default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(null=True, to='products.tag'),
        ),
        migrations.AlterField(
            model_name='product',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(null=True, to='products.photo'),
        ),
    ]
