# Generated by Django 5.1.1 on 2024-09-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_photo_product_price_alter_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(to='products.photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='products.tag'),
        ),
    ]
