# Generated by Django 5.1.1 on 2025-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numSold',
            field=models.IntegerField(default=0),
        ),
    ]
