# Generated by Django 5.1.1 on 2024-09-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='term',
            field=models.IntegerField(blank=True),
        ),
    ]
