# Generated by Django 5.1.1 on 2024-09-29 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_photos_photo_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='label',
        ),
    ]
