# Generated by Django 5.1.1 on 2025-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_firstphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='firstPhoto',
            field=models.CharField(blank=True, null=True),
        ),
    ]
