# Generated by Django 5.1.1 on 2025-02-25 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_firstphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='firstPhoto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
