# Generated by Django 5.1.1 on 2024-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='label',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.FileField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
