# Generated by Django 5.1.1 on 2024-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='', verbose_name='Tamanho (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('fixed', 'Tamanho único'), ('choice', 'Selecionar tamanho'), ('set', 'Definir valor')], default='', verbose_name='Tipo de tamanho'),
        ),
        migrations.AlterField(
            model_name='product',
            name='term',
            field=models.IntegerField(blank=True, verbose_name='Prazo de produção'),
        ),
    ]
