# Generated by Django 5.1.1 on 2025-07-08 16:26

from django.db import migrations


def create_all_tag(apps, schema_editor):
    Tag = apps.get_model('products', 'Tag')
    Tag.objects.create(name='all', numProducts=0)


def remove_all_tag(apps, schema_editor):
    Tag = apps.get_model('products', 'Tag')
    Tag.objects.filter(name='all').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_createdat'),
    ]

    operations = [
        migrations.RunPython(create_all_tag, remove_all_tag),
    ]
