# Generated by Django 5.1.1 on 2024-10-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numPhotos',
            field=models.IntegerField(default=0),
        ),
    ]
